package com.dinet.pedidos.domain.model;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * Modelo de dominio: Pedido (sin anotaciones de persistencia).
 * El dominio mantiene los datos necesarios para las reglas de negocio.
 */
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Pedido {

    private UUID id;
    private String numeroPedido;
    private String clienteId;
    private String zonaId;
    private LocalDate fechaEntrega;
    private EstadoPedido estado;
    private boolean requiereRefrigeracion;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Pedido pedido = (Pedido) o;

        return Objects.equals(numeroPedido, pedido.numeroPedido);
    }

    @Override
    public int hashCode() {
        return numeroPedido != null ? numeroPedido.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "Pedido{" +
                "id=" + id +
                ", numeroPedido='" + numeroPedido + '\'' +
                ", clienteId='" + clienteId + '\'' +
                ", zonaId='" + zonaId + '\'' +
                ", fechaEntrega=" + fechaEntrega +
                ", estado=" + estado +
                ", requiereRefrigeracion=" + requiereRefrigeracion +
                '}';
    }

    // factory helper to create a new Pedido (id autogenerated)
    public static Pedido of(String numeroPedido,
                            String clienteId,
                            String zonaId,
                            LocalDate fechaEntrega,
                            EstadoPedido estado,
                            boolean requiereRefrigeracion) {
        return new Pedido(UUID.randomUUID(), numeroPedido, clienteId, zonaId, fechaEntrega, estado, requiereRefrigeracion);
    }
}
